# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../../data/mainWindow.ui'
#
# Created: Mon Feb 20 17:07:42 2012
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(720, 547)
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "kyuNotebook", None, QtGui.QApplication.UnicodeUTF8))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/application")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(3, 0, 6, 0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pageTab = QtGui.QTabWidget(self.centralwidget)
        self.pageTab.setElideMode(QtCore.Qt.ElideNone)
        self.pageTab.setDocumentMode(False)
        self.pageTab.setTabsClosable(True)
        self.pageTab.setMovable(True)
        self.pageTab.setObjectName(_fromUtf8("pageTab"))
        self.horizontalLayout.addWidget(self.pageTab)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 720, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.fileMenu = QtGui.QMenu(self.menubar)
        self.fileMenu.setTitle(QtGui.QApplication.translate("MainWindow", "파일(&F)", None, QtGui.QApplication.UnicodeUTF8))
        self.fileMenu.setObjectName(_fromUtf8("fileMenu"))
        self.editMenu = QtGui.QMenu(self.menubar)
        self.editMenu.setTitle(QtGui.QApplication.translate("MainWindow", "편집(&E)", None, QtGui.QApplication.UnicodeUTF8))
        self.editMenu.setObjectName(_fromUtf8("editMenu"))
        self.toolMenu = QtGui.QMenu(self.menubar)
        self.toolMenu.setTitle(QtGui.QApplication.translate("MainWindow", "도구(&T)", None, QtGui.QApplication.UnicodeUTF8))
        self.toolMenu.setObjectName(_fromUtf8("toolMenu"))
        self.helpMenu = QtGui.QMenu(self.menubar)
        self.helpMenu.setTitle(QtGui.QApplication.translate("MainWindow", "도움말(&H)", None, QtGui.QApplication.UnicodeUTF8))
        self.helpMenu.setObjectName(_fromUtf8("helpMenu"))
        self.settingMenu = QtGui.QMenu(self.menubar)
        self.settingMenu.setTitle(QtGui.QApplication.translate("MainWindow", "설정(&S)", None, QtGui.QApplication.UnicodeUTF8))
        self.settingMenu.setObjectName(_fromUtf8("settingMenu"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.fileToolBar = QtGui.QToolBar(MainWindow)
        self.fileToolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "도구모음", None, QtGui.QApplication.UnicodeUTF8))
        self.fileToolBar.setMovable(True)
        self.fileToolBar.setFloatable(True)
        self.fileToolBar.setObjectName(_fromUtf8("fileToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.fileToolBar)
        self.noteTreeDockWidget = QtGui.QDockWidget(MainWindow)
        self.noteTreeDockWidget.setWindowTitle(QtGui.QApplication.translate("MainWindow", "노트 트리", None, QtGui.QApplication.UnicodeUTF8))
        self.noteTreeDockWidget.setObjectName(_fromUtf8("noteTreeDockWidget"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.noteTreeDockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.noteTreeDockWidget)
        self.fontToolBar = QtGui.QToolBar(MainWindow)
        self.fontToolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.fontToolBar.setMovable(True)
        self.fontToolBar.setObjectName(_fromUtf8("fontToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.fontToolBar)
        self.quitAction = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/quit")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.quitAction.setIcon(icon1)
        self.quitAction.setText(QtGui.QApplication.translate("MainWindow", "종료", None, QtGui.QApplication.UnicodeUTF8))
        self.quitAction.setToolTip(QtGui.QApplication.translate("MainWindow", "프로그램을 종료합니다.", None, QtGui.QApplication.UnicodeUTF8))
        self.quitAction.setStatusTip(QtGui.QApplication.translate("MainWindow", "프로그램을 종료합니다.", None, QtGui.QApplication.UnicodeUTF8))
        self.quitAction.setObjectName(_fromUtf8("quitAction"))
        self.newPageAction = QtGui.QAction(MainWindow)
        self.newPageAction.setEnabled(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/new_page")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.newPageAction.setIcon(icon2)
        self.newPageAction.setText(QtGui.QApplication.translate("MainWindow", "새 페이지(&P)", None, QtGui.QApplication.UnicodeUTF8))
        self.newPageAction.setToolTip(QtGui.QApplication.translate("MainWindow", "새 페이지를 생성합니다.", None, QtGui.QApplication.UnicodeUTF8))
        self.newPageAction.setStatusTip(QtGui.QApplication.translate("MainWindow", "새 페이지를 생성합니다.", None, QtGui.QApplication.UnicodeUTF8))
        self.newPageAction.setObjectName(_fromUtf8("newPageAction"))
        self.newNoteAction = QtGui.QAction(MainWindow)
        self.newNoteAction.setEnabled(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/new_note")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.newNoteAction.setIcon(icon3)
        self.newNoteAction.setText(QtGui.QApplication.translate("MainWindow", "새 노트(&N)", None, QtGui.QApplication.UnicodeUTF8))
        self.newNoteAction.setToolTip(QtGui.QApplication.translate("MainWindow", "새 노트를 생성합니다.", None, QtGui.QApplication.UnicodeUTF8))
        self.newNoteAction.setStatusTip(QtGui.QApplication.translate("MainWindow", "새 노트를 생성합니다.", None, QtGui.QApplication.UnicodeUTF8))
        self.newNoteAction.setShortcut(_fromUtf8("Ctrl+Shift+N"))
        self.newNoteAction.setObjectName(_fromUtf8("newNoteAction"))
        self.changeNoteDirAction = QtGui.QAction(MainWindow)
        self.changeNoteDirAction.setText(QtGui.QApplication.translate("MainWindow", "노트 폴더 변경", None, QtGui.QApplication.UnicodeUTF8))
        self.changeNoteDirAction.setToolTip(QtGui.QApplication.translate("MainWindow", "노트를 저장하는 폴더를 변경합니다.", None, QtGui.QApplication.UnicodeUTF8))
        self.changeNoteDirAction.setStatusTip(QtGui.QApplication.translate("MainWindow", "노트를 저장하는 폴더를 변경합니다.", None, QtGui.QApplication.UnicodeUTF8))
        self.changeNoteDirAction.setObjectName(_fromUtf8("changeNoteDirAction"))
        self.savePageAction = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/save_page")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.savePageAction.setIcon(icon4)
        self.savePageAction.setText(QtGui.QApplication.translate("MainWindow", "현재 페이지 저장(&S)", None, QtGui.QApplication.UnicodeUTF8))
        self.savePageAction.setToolTip(QtGui.QApplication.translate("MainWindow", "현재 열린 페이지를 저장합니다.", None, QtGui.QApplication.UnicodeUTF8))
        self.savePageAction.setStatusTip(QtGui.QApplication.translate("MainWindow", "현재 열린 페이지를 저장합니다.", None, QtGui.QApplication.UnicodeUTF8))
        self.savePageAction.setObjectName(_fromUtf8("savePageAction"))
        self.saveAllPageAction = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/save_all_page")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveAllPageAction.setIcon(icon5)
        self.saveAllPageAction.setText(QtGui.QApplication.translate("MainWindow", "모든 페이지 저장", None, QtGui.QApplication.UnicodeUTF8))
        self.saveAllPageAction.setToolTip(QtGui.QApplication.translate("MainWindow", "현재 열려있는 모든 페이지를 저장합니다.", None, QtGui.QApplication.UnicodeUTF8))
        self.saveAllPageAction.setStatusTip(QtGui.QApplication.translate("MainWindow", "현재 열려있는 모든 페이지를 저장합니다.", None, QtGui.QApplication.UnicodeUTF8))
        self.saveAllPageAction.setObjectName(_fromUtf8("saveAllPageAction"))
        self.changeTitleAction = QtGui.QAction(MainWindow)
        self.changeTitleAction.setText(QtGui.QApplication.translate("MainWindow", "이름 바꾸기", None, QtGui.QApplication.UnicodeUTF8))
        self.changeTitleAction.setToolTip(QtGui.QApplication.translate("MainWindow", "노트나 페이지의 이름을 변경합니다.", None, QtGui.QApplication.UnicodeUTF8))
        self.changeTitleAction.setStatusTip(QtGui.QApplication.translate("MainWindow", "노트나 페이지의 이름을 변경합니다.", None, QtGui.QApplication.UnicodeUTF8))
        self.changeTitleAction.setShortcut(_fromUtf8("F2"))
        self.changeTitleAction.setObjectName(_fromUtf8("changeTitleAction"))
        self.editPageAction = QtGui.QAction(MainWindow)
        self.editPageAction.setEnabled(False)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/edit_page")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editPageAction.setIcon(icon6)
        self.editPageAction.setText(QtGui.QApplication.translate("MainWindow", "페이지 편집(&E)", None, QtGui.QApplication.UnicodeUTF8))
        self.editPageAction.setToolTip(QtGui.QApplication.translate("MainWindow", "선택한 페이지를 편집합니다.", None, QtGui.QApplication.UnicodeUTF8))
        self.editPageAction.setStatusTip(QtGui.QApplication.translate("MainWindow", "선택한 페이지를 편집합니다.", None, QtGui.QApplication.UnicodeUTF8))
        self.editPageAction.setObjectName(_fromUtf8("editPageAction"))
        self.removeItemAction = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/remove_item")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.removeItemAction.setIcon(icon7)
        self.removeItemAction.setText(QtGui.QApplication.translate("MainWindow", "노트/페이지 제거", None, QtGui.QApplication.UnicodeUTF8))
        self.removeItemAction.setToolTip(QtGui.QApplication.translate("MainWindow", "선택한 노트나 페이지를 제거합니다.", None, QtGui.QApplication.UnicodeUTF8))
        self.removeItemAction.setStatusTip(QtGui.QApplication.translate("MainWindow", "선택한 노트나 페이지를 제거합니다.", None, QtGui.QApplication.UnicodeUTF8))
        self.removeItemAction.setObjectName(_fromUtf8("removeItemAction"))
        self.closeCurrentPageAction = QtGui.QAction(MainWindow)
        self.closeCurrentPageAction.setText(QtGui.QApplication.translate("MainWindow", "현재 페이지 닫기", None, QtGui.QApplication.UnicodeUTF8))
        self.closeCurrentPageAction.setToolTip(QtGui.QApplication.translate("MainWindow", "현재 열린 페이지를 닫습니다.", None, QtGui.QApplication.UnicodeUTF8))
        self.closeCurrentPageAction.setStatusTip(QtGui.QApplication.translate("MainWindow", "현재 열린 페이지를 닫습니다.", None, QtGui.QApplication.UnicodeUTF8))
        self.closeCurrentPageAction.setObjectName(_fromUtf8("closeCurrentPageAction"))
        self.aboutAction = QtGui.QAction(MainWindow)
        self.aboutAction.setText(QtGui.QApplication.translate("MainWindow", "kyuNotebook 정보", None, QtGui.QApplication.UnicodeUTF8))
        self.aboutAction.setToolTip(QtGui.QApplication.translate("MainWindow", "kyuNotebook에 대한 정보를 보여줍니다.", None, QtGui.QApplication.UnicodeUTF8))
        self.aboutAction.setStatusTip(QtGui.QApplication.translate("MainWindow", "kyuNotebook에 대한 정보를 보여줍니다.", None, QtGui.QApplication.UnicodeUTF8))
        self.aboutAction.setObjectName(_fromUtf8("aboutAction"))
        self.fontAction = QtGui.QAction(MainWindow)
        self.fontAction.setText(QtGui.QApplication.translate("MainWindow", "글꼴(&F)", None, QtGui.QApplication.UnicodeUTF8))
        self.fontAction.setToolTip(QtGui.QApplication.translate("MainWindow", "글꼴을 변경합니다.", None, QtGui.QApplication.UnicodeUTF8))
        self.fontAction.setStatusTip(QtGui.QApplication.translate("MainWindow", "글꼴을 변경합니다.", None, QtGui.QApplication.UnicodeUTF8))
        self.fontAction.setObjectName(_fromUtf8("fontAction"))
        self.boldAction = QtGui.QAction(MainWindow)
        self.boldAction.setCheckable(True)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/bold")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boldAction.setIcon(icon8)
        self.boldAction.setText(QtGui.QApplication.translate("MainWindow", "굵게", None, QtGui.QApplication.UnicodeUTF8))
        self.boldAction.setToolTip(QtGui.QApplication.translate("MainWindow", "글꼴을 굵게 표시합니다. (Ctrl+B)", None, QtGui.QApplication.UnicodeUTF8))
        self.boldAction.setStatusTip(QtGui.QApplication.translate("MainWindow", "글꼴을 굵게 표시합니다.", None, QtGui.QApplication.UnicodeUTF8))
        self.boldAction.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+B", None, QtGui.QApplication.UnicodeUTF8))
        self.boldAction.setObjectName(_fromUtf8("boldAction"))
        self.italicAction = QtGui.QAction(MainWindow)
        self.italicAction.setCheckable(True)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/italic")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.italicAction.setIcon(icon9)
        self.italicAction.setText(QtGui.QApplication.translate("MainWindow", "이탤릭체", None, QtGui.QApplication.UnicodeUTF8))
        self.italicAction.setToolTip(QtGui.QApplication.translate("MainWindow", "글꼴을 기울려서 표시합니다. (Ctrl+I)", None, QtGui.QApplication.UnicodeUTF8))
        self.italicAction.setStatusTip(QtGui.QApplication.translate("MainWindow", "글꼴을 기울려서 표시합니다.", None, QtGui.QApplication.UnicodeUTF8))
        self.italicAction.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+I", None, QtGui.QApplication.UnicodeUTF8))
        self.italicAction.setObjectName(_fromUtf8("italicAction"))
        self.underlineAction = QtGui.QAction(MainWindow)
        self.underlineAction.setCheckable(True)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/underline")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.underlineAction.setIcon(icon10)
        self.underlineAction.setText(QtGui.QApplication.translate("MainWindow", "밑줄", None, QtGui.QApplication.UnicodeUTF8))
        self.underlineAction.setToolTip(QtGui.QApplication.translate("MainWindow", "글꼴에 밑줄을 표시합니다. (Ctrl+U)", None, QtGui.QApplication.UnicodeUTF8))
        self.underlineAction.setStatusTip(QtGui.QApplication.translate("MainWindow", "글꼴에 밑줄을 표시합니다.", None, QtGui.QApplication.UnicodeUTF8))
        self.underlineAction.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+U", None, QtGui.QApplication.UnicodeUTF8))
        self.underlineAction.setObjectName(_fromUtf8("underlineAction"))
        self.strikeoutAction = QtGui.QAction(MainWindow)
        self.strikeoutAction.setCheckable(True)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/strikeout")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.strikeoutAction.setIcon(icon11)
        self.strikeoutAction.setText(QtGui.QApplication.translate("MainWindow", "취소선", None, QtGui.QApplication.UnicodeUTF8))
        self.strikeoutAction.setToolTip(QtGui.QApplication.translate("MainWindow", "글꼴에 취소선을 표시합니다. (Ctrl+D)", None, QtGui.QApplication.UnicodeUTF8))
        self.strikeoutAction.setStatusTip(QtGui.QApplication.translate("MainWindow", "글꼴에 취소선을 표시합니다.", None, QtGui.QApplication.UnicodeUTF8))
        self.strikeoutAction.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+D", None, QtGui.QApplication.UnicodeUTF8))
        self.strikeoutAction.setObjectName(_fromUtf8("strikeoutAction"))
        self.fileMenu.addAction(self.newNoteAction)
        self.fileMenu.addAction(self.newPageAction)
        self.fileMenu.addSeparator()
        self.fileMenu.addAction(self.editPageAction)
        self.fileMenu.addAction(self.removeItemAction)
        self.fileMenu.addSeparator()
        self.fileMenu.addAction(self.savePageAction)
        self.fileMenu.addAction(self.saveAllPageAction)
        self.fileMenu.addSeparator()
        self.fileMenu.addAction(self.changeNoteDirAction)
        self.fileMenu.addSeparator()
        self.fileMenu.addAction(self.closeCurrentPageAction)
        self.fileMenu.addAction(self.quitAction)
        self.editMenu.addAction(self.changeTitleAction)
        self.toolMenu.addAction(self.fontAction)
        self.helpMenu.addAction(self.aboutAction)
        self.menubar.addAction(self.fileMenu.menuAction())
        self.menubar.addAction(self.editMenu.menuAction())
        self.menubar.addAction(self.toolMenu.menuAction())
        self.menubar.addAction(self.settingMenu.menuAction())
        self.menubar.addAction(self.helpMenu.menuAction())
        self.fileToolBar.addAction(self.newNoteAction)
        self.fileToolBar.addAction(self.newPageAction)
        self.fileToolBar.addSeparator()
        self.fileToolBar.addAction(self.editPageAction)
        self.fileToolBar.addAction(self.savePageAction)
        self.fontToolBar.addAction(self.boldAction)
        self.fontToolBar.addAction(self.italicAction)
        self.fontToolBar.addAction(self.underlineAction)
        self.fontToolBar.addAction(self.strikeoutAction)

        self.retranslateUi(MainWindow)
        self.pageTab.setCurrentIndex(-1)
        QtCore.QObject.connect(self.quitAction, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        pass

from . import icons_rc
